// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvpvlhywwjpxpvniagfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2cHZsaHl3d2pweHB2bmlhZ2ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzc2OTQsImV4cCI6MjA2OTkxMzY5NH0.RtS16x1dYttL1cY1U9lIYYvUDGo-EV6hMitRTqB-EgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit',
    debug: true
  }
});